defaults:
  - outputs
  - base_config
  - api: main
  - dataset: hotpot_qa
  - metric: hotpot_qa
  - _self_

_target_: "src.util.unit_test"

generate_func:
  _target_: "src.util.dry_run"

output_func:
  _target_: "src.util.write_output"